### ISSUE TITLE
Error when downloading papers from Pubmed.

### ISSUE THREAD

**Issue by doubleplusplus** [PhosphorylatedRabbits/paperscraper#40]
when I tried to download papers from pubmed, I got this error:

JSONDecodeError: Invalid control character at: line 1 column 105 (char 104)

**Comment by jannisborn** [comment]
Sorry to hear. Could you please report the full command and trace back of the error. Thanks !

**Comment by jannisborn** [comment]
The error is not inside paperscraper but originates from `pymed`, which we use to access the PubMed API. Pymed package has been archived and is no longer maintained. The reason lies in the PubMed API which returns strings that cannot be jsonified because the include a newline character. Interestingly the same issue has been observed in `BioPython` another python package leveraging PubMed API: https://stackoverflow.com/questions/75353091/biopython-entrez-article-limit

The hotfix is to pass `max_results=9999` to `get_and_dump_pubmed_papers`. This argument will be passed down to the PubMed query handler. The reason for the bug is this message from PubMed API:

_RuntimeError: Search Backend failed: Exception:
'retstart' cannot be larger than 9998. For PubMed, 
ESearch can only retrieve the first 9,999 records 
matching the query.
 To obtain more than 9,999 PubMed records, consider 
using EDirect that contains additional logic 
to batch PubMed search results automatically
 so that an arbitrary number can be retrieved.
 For details see https://www.ncbi.nlm.nih.gov/books/NBK25499/_
 
 The issue in paperscraper is that max_results defaults to 9999999. I will adapt the default for the next release, for the time being please always set the parameter manually and it should work ;)

**Comment by jannisborn** [comment]
Released a new version `0.2.11` that supports the new behaviour by default, see #41 for details @doubleplusplus
